---
abstract: 'Twitter/IRC gateway'
author:
  - 'Marc Mims <marc@questright.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-Twirc
no_index:
  directory:
    - inc
    - t
requires:
  Email::Valid: 0
  FindBin: 0
  LWP::UserAgent::POE: 0.02
  Log::Log4perl: 0
  MooseX::Getopt: 0.15
  MooseX::Log::Log4perl::Easy: 0
  MooseX::POE: 0
  MooseX::SimpleConfig: 0
  MooseX::Storage: 0
  Net::Twitter: 3.04002
  POE::Component::Server::IRC: 0.02005
  POE::Component::TSTP: 0
  Path::Class::File: 0
  Proc::Daemon: 0
  Text::Truncate: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/semifor/twirc.git
version: 0.07
