---
abstract: 'Twitter/IRC gateway'
author:
  - 'Marc Mims <marc@questright.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-Twirc
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent::Twitter::Stream: 0.23
  Config::Any: 0
  Encode: 0
  FindBin: 0
  HTML::Entities: 0
  LWP::UserAgent::POE: 0.02
  Log::Log4perl: 0
  Moose: 0
  MooseX::Getopt: 0.15
  MooseX::Log::Log4perl::Easy: 0
  MooseX::POE: 0.215
  MooseX::SimpleConfig: 0
  MooseX::Storage: 0
  Net::Twitter: 4.00006
  POE::Component::Server::IRC: 0.02005
  POE::Component::TSTP: 0
  Path::Class::File: 0
  Proc::Daemon: 0
  Regexp::Common::URI: 0
  Scalar::Util: 0
  String::Truncate: 0
  Try::Tiny: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/semifor/twirc.git
version: 0.17
